### ISSUE TITLE
🐞 #Bug Fix --trash directive

### ISSUE THREAD

**Issue by ldexterldesign** [jmathai/elodie#121]
Hey,

Hope you're well

Thanks for awesome software

I'm currently unable to use the --trash directive

I'm using the latest version and believe I've upgraded all requirements, but still no luck...

Device: Apple MBP (desktop)
Platform: OS X
Type: Desktop
Version: 10.11.3

```bash
Apple-MacBook-Pro:~ ldexterldesign$ cd /Applications/elodie/
Apple-MacBook-Pro:elodie ldexterldesign$ ./elodie.py import --source="/Volumes/server/_todo/image/_1" --destination="/Volumes/server/_todo/image/_2" --trash
Traceback (most recent call last):
  File "./elodie.py", line 232, in <module>
    main()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 98, in _import
    trash)
  File "./elodie.py", line 61, in import_file
    send2trash(_file)
  File "/Library/Python/2.7/site-packages/send2trash/plat_osx.py", line 48, in send2trash
    check_op_result(op_result)
  File "/Library/Python/2.7/site-packages/send2trash/plat_osx.py", line 37, in check_op_result
    raise OSError(msg)
OSError: Directory not found
Apple-MacBook-Pro:elodie ldexterldesign$ pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): click<7.0,>=6.2 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): requests<3.0,>=2.9.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): send2trash<2.0,>=1.3.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3))
Apple-MacBook-Pro:elodie ldexterldesign$ pip install -r requirements.txt --upgrade
Requirement already up-to-date: click<7.0,>=6.2 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: requests<3.0,>=2.9.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: send2trash<2.0,>=1.3.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3))
```

Are there currently any known issues and/or can you help fix it?

Hope to hear back

Kind regards

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by jmathai** [comment]
@ldexterldesign do you happen to know which file this fails on? Curious if there are some special characters in the file name that are causing issues. You should be able to see the last processed file in the script's output.

[Here's the line](https://github.com/hsoft/send2trash/blob/master/send2trash/plat_osx.py#L37) from `send2trash` which is causing the error.

**Comment by ldexterldesign** [comment]
Cheers for reply

App' fails on the first file:

```bash
Apple-MacBook-Pro:~ ldexterldesign$ cd /Applications/Elodie/
Apple-MacBook-Pro:Elodie ldexterldesign$ ./elodie.py import --source="/Volumes/server/_todo/image/_1" --destination="/Volumes/server/_todo/image/_3" --trash
/Volumes/server/_todo/image/_1/20131121/2013-01-13 17.15.48-1.jpg -> /Volumes/server/_todo/image/_3/2013-01-Jan/Unknown Location/2013-01-13_16-15-48-2013-01-13 17.15.48-1.jpg
Traceback (most recent call last):
  File "./elodie.py", line 232, in <module>
    main()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 98, in _import
    trash)
  File "./elodie.py", line 61, in import_file
    send2trash(_file)
  File "/Library/Python/2.7/site-packages/send2trash/plat_osx.py", line 48, in send2trash
    check_op_result(op_result)
  File "/Library/Python/2.7/site-packages/send2trash/plat_osx.py", line 37, in check_op_result
    raise OSError(msg)
OSError: Directory not found
```

Hope to hear back

Kind regards

**Comment by ldexterldesign** [comment]
BUMP

**Comment by jmathai** [comment]
@ldexterldesign Do you mind trying the following and confirming you get the same results?

```
(elodie) ➜  elodie git:(master) ✗ touch text.txt
(elodie) ➜  elodie git:(master) ✗ python
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from send2trash import send2trash
>>> send2trash('text.txt')
>>>
(elodie) ➜  elodie git:(master) ✗ ls text.txt
ls: text.txt: No such file or directory
```

**Comment by ldexterldesign** [comment]
Cheers for reply

```bash
Apple-MacBook-Pro:~ ldexterldesign$ touch text.txt
Apple-MacBook-Pro:~ ldexterldesign$ python
Python 2.7.12 (default, Jun 29 2016, 14:05:02) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from send2trash import send2trash
>>> send2trash('text.txt')
>>> ls text.txt
  File "<stdin>", line 1
    ls text.txt
          ^
SyntaxError: invalid syntax
>>> 
Apple-MacBook-Pro:~ ldexterldesign$ ls text.txt
ls: text.txt: No such file or directory
Apple-MacBook-Pro:~ ldexterldesign$ pwd
/Users/ldexterldesign
Apple-MacBook-Pro:~ ldexterldesign$ ls /Users/ldexterldesign/text.txt
ls: /Users/ldexterldesign/text.txt: No such file or directory
Apple-MacBook-Pro:~ ldexterldesign$ 
```

Hope this is useful

Kind thanks

**Comment by jmathai** [comment]
What about `ls /Users/ldexterldesign/.Trash/text.txt`?

Is this the computer you're running elodie on and getting this error?

**Comment by ldexterldesign** [comment]
Apologies for delay

Cheers for reply

I tried a more localised OS X install this time (i.e. ``/Users/ldexterldesign/Applications`` rather than ``/Applications``) and everything working fine now

Out of interest, where do you install your default OS X apps?:

```
/Applications
~/Applications
```

Kind thanks

**Comment by jmathai** [comment]
Thanks for following up. I install git repos somewhere in my home directory and not alongside other apps.

**Comment by ldexterldesign** [comment]
FYI Same issue this evening, after a clean OS install. I localised the install like https://github.com/jmathai/elodie/issues/121#issuecomment-239715489 but, unfortunately, hasn't fixed things this time...

Regards

**Comment by jmathai** [comment]
@ldexterldesign I added tests for the `--trash` (#165) option and I'm not able to reproduce a problem. Did you want to reopen this and try to troubleshoot your issue?

**Comment by jmathai** [comment]
FWIW the tests pass on my laptop (OS X) and on TravisCI (Debian Linux).

**Comment by ldexterldesign** [comment]
I moved both my source and destination files from ``/Volumes/synology`` (Linux), which is my NAS, to ``/Users/ldexterldesign/Desktop`` (OS X) and ``--trash`` works

Besides possibly permissions, can you think why running OS X commands on an external volume / file system may not work?

Yours hopefully

**Comment by ldexterldesign** [comment]
Follow up

Nope, nothing to do with file name/path syntax AFAIC

I setup a test at the root of my NAS in simple source and destination folders containing no spaces and use of ``--trash`` failed

I then setup a test on my desktop using complex (i.e. long file names with spaces) source and destination folders and use of ``--trash`` succeeded

Let me know if you have any issue - happy to help

Hope this is useful

Regards

**Comment by jmathai** [comment]
@ldexterldesign I believe the issue is that you're running the code on OS X but trying to send a file on a linux system to the trash. Since the code being run is only aware of the operating system it's executing on it's not able to locate the trash on another system.

The send2trash module we're use for the `--trash` option runs different code based on the OS.

**Comment by ldexterldesign** [comment]
Cheers for reply

Needless to say, glad we got to the bottom of that one!

Keep up the great work

Kind thanks
