### ISSUE TITLE
Javascript error when running app

### ISSUE THREAD

**Issue by martinsondergaard** [jmathai/elodie#122]
Hey

This project seem like just the thing I'm looking for, but I really need the GUI app to work.
After having quite a bit of trouble getting node.js and electron installed I finally managed to build the app. However, when I try and run the .exe I get a javascript error

```
A JavaScript error occurred in the main process

Uncaught Exception
Error: Cannot find module 'menubar'
    at Function.Module._resolverFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:7)
    at Object.<anonymous>
(C:\...\Elodie-win32-x64\resources\app\app\module...:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Do you have an idea what is causing this, and how to fix it?
Is it a bug with the windows desktop app or am I doing something wrong?

**Comment by zserg** [comment]
Hello,
You have to install menubar module:
`npm install menubar`

**Comment by jmathai** [comment]
You can get all of the dependencies by running `npm i` from the root of the repository. That will include `menubar`.

The menubar app is still in alpha so please reopen if you still have issues.
