### ISSUE TITLE
#Bug #Help Fix/research UnicodeDecodeError: 'utf8' codec... decode bytes...

### ISSUE THREAD

**Issue by ldexterldesign** [jmathai/elodie#127]
Hey,

Thanks for software, as always

Hope you're well

An error popped up tonight and wondered if you can help?:

```
Apple-MacBook-Pro:Elodie ldexterldesign$ ./elodie.py import --source="/Users/ldexterldesign/Desktop/01" --destination="/Users/ldexterldesign/Desktop/02" --trash
Traceback (most recent call last):
  File "./elodie.py", line 233, in <module>
    main()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 99, in _import
    trash)
  File "./elodie.py", line 58, in import_file
    media, allowDuplicate=False, move=False)
  File "/Users/ldexterldesign/Applications/Elodie/elodie/filesystem.py", line 184, in process_file
    metadata = media.get_metadata()
  File "/Users/ldexterldesign/Applications/Elodie/elodie/media/base.py", line 87, in get_metadata
    'date_taken': self.get_date_taken(),
  File "/Users/ldexterldesign/Applications/Elodie/elodie/media/photo.py", line 76, in get_date_taken
    exif = self.get_exiftool_attributes()
  File "/Users/ldexterldesign/Applications/Elodie/elodie/media/media.py", line 119, in get_exiftool_attributes
    metadata = et.get_metadata(source)
  File "/Users/ldexterldesign/Applications/Elodie/elodie/external/pyexiftool.py", line 323, in get_metadata
    return self.execute_json(filename)[0]
  File "/Users/ldexterldesign/Applications/Elodie/elodie/external/pyexiftool.py", line 307, in execute_json
    return json.loads(self.execute(b"-j", *params).decode("utf-8"))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 15854-15855: invalid continuation byte
```

Sample (problem) image:

![imgp1292](https://cloud.githubusercontent.com/assets/1715809/18332512/6ee4cde2-7567-11e6-9b27-1a2bcc94b143.JPG)

Hope to hear back

Yours faithfully

**Comment by jmathai** [comment]
Thanks for reporting. It's been fixed and merged into master.

The problem was with the utf-8 decoding so we're now falling back to latin if it fails.

**Comment by ldexterldesign** [comment]
Apologies for delay

Thanks for fix - works great

Kind thanks

PS Still finding your software really useful!
