### ISSUE TITLE
Crash if longitude is 0

### ISSUE THREAD

**Issue by vorg** [jmathai/elodie#171]
Trying to import photo taken above London at 51' N, 0' W crashes with `ValueError: could not convert string to float`.

Here is exif data extracted via exiftool

```
GPS Latitude                    : 51 deg 33' 11.70" N
GPS Longitude                   : 0 deg 0' 15.04" W
```

Error log

```
Traceback (most recent call last):
  File "./elodie.py", line 301, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 111, in _import
    trash, allow_duplicates)
  File "./elodie.py", line 64, in import_file
    media, allowDuplicate=allow_duplicates, move=False)
  File "/Users/vorg/Dev/elodie/elodie/filesystem.py", line 191, in process_file
    directory_name = self.get_folder_path(metadata)
  File "/Users/vorg/Dev/elodie/elodie/filesystem.py", line 163, in get_folder_path
    metadata['longitude']
  File "/Users/vorg/Dev/elodie/elodie/geolocation.py", line 124, in place_name
    lon = float(lon)
ValueError: could not convert string to float:
```

I logged input to `place_name` and the latitude is missing. Maybe "false" values in exif data are skipped while parsing?

```
place_name "51.55325" ""
```

**Comment by jmathai** [comment]
Can you send me the file you're having trouble with? I'm not able to reproduce the issue using a file with longitude `0 deg 0' 16.35" W`.

**Comment by vorg** [comment]
@jmathai the failing photo should be in your inbox.

**Comment by vorg** [comment]
Updated the title with longitude not latitude.

@jmathai Also i've sent you another photo that crashed at

Latitude: 51° 32’ 37.74” N
Longitude: 0° 0’ 17.88” W

**Comment by jmathai** [comment]
Thanks @vorg. Looks like a bug in pyexiftool. It parses the longitude as a string.

```
  "Composite:GPSLatitude": 51.55325,
  "Composite:GPSLongitude": "-0.00417777777777778",
```

**Comment by jmathai** [comment]
For reference, I've opened a bug to fix the underlying issue in exiftool but will patch it in our code as well.

http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,7952.0.html

**Comment by jmathai** [comment]
Fix is available in master. Please reopen if you still have issues.
