### ISSUE TITLE
Source path with only digits aborts process

### ISSUE THREAD

**Issue by ojacques** [jmathai/elodie#239]
I have some of my source tree which has only digits (like `20120510`).
This makes Elodie stop with the following backtrace:

```
Traceback (most recent call last):
  File "./elodie.py", line 345, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 115, in _import
    trash, allow_duplicates)
  File "./elodie.py", line 64, in import_file
    media, allowDuplicate=allow_duplicates, move=False)
  File "/root/elodie/elodie/filesystem.py", line 339, in process_file
    directory_name = self.get_folder_path(metadata)
  File "/root/elodie/elodie/filesystem.py", line 261, in get_folder_path
    return os.path.join(*path)
  File "/usr/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'int' object has no attribute 'startswith'
```

In [elodie/filesystem.py](https://github.com/jmathai/elodie/blob/master/elodie/filesystem.py#L261), it seems python converts this path as a number, which makes the path.join fail.

Thanks !

**Comment by jmathai** [comment]
I added [a few tests](https://github.com/jmathai/elodie/pull/241) to reproduce the failure but could not do so.

I have tests which include in the PR.
* Source path contains folders with just numbers.
* Config file has a `full_path` with just numbers.

Can you provide more information?

**Comment by jmathai** [comment]
Here are sample paths from the tests which pass.

Source path `/var/folders/gs/m8633l3x3fl8wwg67c0mrktr0000gn/T/8416140984/1801682778/plain.jpg`

`full_path` actually converts to a string. `['2015']` in my test.

**Comment by Chnkr** [comment]
I ran into this issue as well.

```
Traceback (most recent call last):
  File "./elodie.py", line 345, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 115, in _import
    trash, allow_duplicates)
  File "./elodie.py", line 64, in import_file
    media, allowDuplicate=allow_duplicates, move=False)
  File "/opt/elodie/elodie/filesystem.py", line 339, in process_file
    directory_name = self.get_folder_path(metadata)
  File "/opt/elodie/elodie/filesystem.py", line 261, in get_folder_path
    return os.path.join(*path)
  File "/usr/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'int' object has no attribute 'startswith'
```

Running the following config

```
[Directory]
month=%m
year=%Y
day=%d
full_path=%year/%month/%day/%album
```


I've added a `print()` statement that dumps the `*path` and it seems to happen with the following path.

```
['2010', '07', '26', 26]
```
