### ISSUE TITLE
Fix "ValueError: No JSON object could be decoded"

### ISSUE THREAD

**Issue by ldexterldesign** [jmathai/elodie#277]
Hey Jaisen,

Hope you're well

Thanks for continued work on Elodie

I have a new issue today I hope we can fix together:

```bash
Lewiss-MacBook-Pro:~ ldexterldesign$ cd ~/elodie/
Lewiss-MacBook-Pro:elodie ldexterldesign$ ls -la
total 192
drwxr-xr-x   3 ldexterldesign  staff     96 24 Jun 18:01 -destination
drwxr-xr-x   9 ldexterldesign  staff    288 24 Jun 18:01 -source
drwxr-xr-x  24 ldexterldesign  staff    768 24 Jun 18:02 .
drwxr-xr-x+ 41 ldexterldesign  staff   1312 24 Jun 19:48 ..
-rw-r--r--@  1 ldexterldesign  staff   6148 24 Jun 18:10 .DS_Store
-rw-r--r--   1 ldexterldesign  staff     61 24 Jun 15:21 .coveragerc
-rw-r--r--   1 ldexterldesign  staff      5 24 Jun 15:21 .dockerignore
drwxr-xr-x  12 ldexterldesign  staff    384 24 Jun 15:21 .git
-rw-r--r--   1 ldexterldesign  staff    120 24 Jun 15:21 .gitignore
-rwxr-xr-x   1 ldexterldesign  staff     89 24 Jun 15:21 .pre-commit
-rw-r--r--   1 ldexterldesign  staff    985 24 Jun 15:21 .travis.yml
-rw-r--r--   1 ldexterldesign  staff   1231 24 Jun 15:21 Dockerfile
-rw-r--r--   1 ldexterldesign  staff  10849 24 Jun 15:21 LICENSE
-rw-r--r--   1 ldexterldesign  staff  17777 24 Jun 15:21 Readme.md
drwxr-xr-x   6 ldexterldesign  staff    192 24 Jun 15:21 app
-rw-r--r--   1 ldexterldesign  staff     38 24 Jun 15:21 config.ini-sample
drwxr-xr-x   3 ldexterldesign  staff     96 24 Jun 15:21 configs
drwxr-xr-x   4 ldexterldesign  staff    128 24 Jun 15:21 creative
drwxr-xr-x   6 ldexterldesign  staff    192 24 Jun 15:21 docs
drwxr-xr-x  27 ldexterldesign  staff    864 24 Jun 18:04 elodie
-rwxr-xr-x   1 ldexterldesign  staff  12597 24 Jun 15:21 elodie.py
-rw-r--r--   1 ldexterldesign  staff    896 24 Jun 15:21 elodie.spec
-rw-r--r--   1 ldexterldesign  staff    490 24 Jun 15:21 package.json
-rw-r--r--   1 ldexterldesign  staff     97 24 Jun 15:21 requirements.txt
Lewiss-MacBook-Pro:elodie ldexterldesign$ python --version
Python 2.7.10
Lewiss-MacBook-Pro:elodie ldexterldesign$ type python
python is hashed (/usr/bin/python)
Lewiss-MacBook-Pro:elodie ldexterldesign$ ./elodie.py import --source="-source" --destination="-destination"
Traceback (most recent call last):
  File "./elodie.py", line 345, in <module>
    main()
  File "/Users/ldexterldesign/Library/Python/2.7/lib/python/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ldexterldesign/Library/Python/2.7/lib/python/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/ldexterldesign/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ldexterldesign/Library/Python/2.7/lib/python/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ldexterldesign/Library/Python/2.7/lib/python/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 115, in _import
    trash, allow_duplicates)
  File "./elodie.py", line 64, in import_file
    media, allowDuplicate=allow_duplicates, move=False)
  File "/Users/ldexterldesign/elodie/elodie/filesystem.py", line 336, in process_file
    media.set_original_name()
  File "/Users/ldexterldesign/elodie/elodie/media/media.py", line 286, in set_original_name
    if self.get_original_name() is not None:
  File "/Users/ldexterldesign/elodie/elodie/media/media.py", line 183, in get_original_name
    exiftool_attributes = self.get_exiftool_attributes()
  File "/Users/ldexterldesign/elodie/elodie/media/media.py", line 131, in get_exiftool_attributes
    metadata = et.get_metadata(source)
  File "/Users/ldexterldesign/elodie/elodie/external/pyexiftool.py", line 330, in get_metadata
    return self.execute_json(filename)[0]
  File "/Users/ldexterldesign/elodie/elodie/external/pyexiftool.py", line 312, in execute_json
    return json.loads(self.execute(b"-j", *params).decode("utf-8"))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Lewiss-MacBook-Pro:elodie ldexterldesign$ pwd
/Users/ldexterldesign/elodie
Lewiss-MacBook-Pro:elodie ldexterldesign$
```

Perhaps this is a known issue/bug?

Let me know if you have any issues - happy to help

Hope this is clear/useful and to hear back

Yours faithfully

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
FYI
NO REPLY NECESSARY

Hope you're well

Thanks for software as always

Between the native mac OS Python and https://brew.sh/ Python I managed to completely jank up my Python install. Anyway I resolved this by installing https://github.com/pyenv/pyenv this week.

Hope this is useful to someone

Keep up great work!

Regards
