### ISSUE TITLE
Video test for get_date_taken fails on Travis but not locally

### ISSUE THREAD

**Issue by jmathai** [jmathai/elodie#32]
```
FAIL: elodie.tests.media.video_test.test_get_date_taken
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/jmathai/elodie/elodie/tests/media/video_test.py", line 58, in test_get_date_taken
    assert date_taken == (2015, 1, 19, 12, 45, 11, 0, 19, 0), date_taken
AssertionError: time.struct_time(tm_year=2015, tm_mon=12, tm_mday=12, tm_hour=8, tm_min=59, tm_sec=26, tm_wday=5, tm_yday=346, tm_isdst=0)
```

**Comment by noonat** [comment]
I think this is failing because of the old exiftool version used for the Travis builds. Travis builds appear to be running on Ubuntu 12.04, and the exiftool installed on Precise is 8.60. The exif data output for this test looks like:

```
File Name                       : video.mov
Directory                       : /root/noonat/elodie/elodie/tests/files
File Size                       : 2.3 MB
File Modification Date/Time     : 2016:01:19 17:40:51+00:00
File Permissions                : rw-r--r--
File Type                       : MOV
MIME Type                       : video/quicktime
Major Brand                     : Apple QuickTime (.MOV/QT)
Minor Version                   : 0.0.0
Compatible Brands               : qt
Movie Data Size                 : 2430692
Movie Header Version            : 0
Modify Date                     : 2015:12:12 08:59:26
Time Scale                      : 600
Duration                        : 1.01 s
Preferred Rate                  : 1
Preferred Volume                : 100.00%
Preview Time                    : 0 s
Preview Duration                : 0 s
Poster Time                     : 0 s
Selection Time                  : 0 s
Selection Duration              : 0 s
Current Time                    : 0 s
Next Track ID                   : 3
Track Header Version            : 0
Track Create Date               : 2015:12:12 08:59:26
Track Modify Date               : 2015:12:12 08:59:26
Track ID                        : 1
Track Duration                  : 1.01 s
Track Layer                     : 0
Track Volume                    : 0.00%
Image Width                     : 1920
Image Height                    : 1080
Graphics Mode                   : ditherCopy
Op Color                        : 32768 32768 32768
Compressor ID                   : avc1
Source Image Width              : 1920
Source Image Height             : 1080
X Resolution                    : 72
Y Resolution                    : 72
Compressor Name                 : H.264
Bit Depth                       : 24
Video Frame Rate                : 29.952
Matrix Structure                : 1 0 0 0 1 0 0 0 1
Media Header Version            : 0
Media Create Date               : 2015:12:12 08:59:26
Media Modify Date               : 2015:12:12 08:59:26
Media Time Scale                : 44100
Media Duration                  : 1.07 s
Media Language Code             : und
Balance                         : 0
Handler Class                   : Data Handler
Handler Vendor ID               : Apple
Handler Description             : Core Media Data Handler
Audio Channels                  : 1
Audio Bits Per Sample           : 16
Audio Sample Rate               : 44100
Audio Format                    : chan
Software Version                : 8.1.2
Create Date                     : 2015:01:19 12:45:11-08:00
GPS Coordinates                 : 38 deg 11' 21.48" N, 119 deg 57' 20.88" W, 2004 m Above Sea Level
Make                            : Apple
Model                           : iPhone 5
Handler Type                    : Metadata Tags
Make (und-US)                   : Apple
Creation Date (und-US)          : 2015:01:19 12:45:11-08:00
GPS Coordinates (und-US)        : 38 deg 11' 21.48" N, 119 deg 57' 20.88" W, 2004 m Above Sea Level
Software (und-US)               : 8.1.2
Model (und-US)                  : iPhone 5
Avg Bitrate                     : 19.3 Mbps
GPS Altitude                    : 2004 m
GPS Altitude Ref                : Above Sea Level
GPS Latitude                    : 38 deg 11' 21.48" N
GPS Longitude                   : 119 deg 57' 20.88" W
GPS Position                    : 38 deg 11' 21.48" N, 119 deg 57' 20.88" W
Image Size                      : 1920x1080
Rotation                        : 0
```

And for exiftool 10.05 running locally, it looks like:

```
File Name                       : video.mov
Directory                       : /Users/nathano/Source/noonat/elodie/elodie/tests/files
File Size                       : 2.3 MB
File Modification Date/Time     : 2016:01:18 11:39:09+00:00
File Access Date/Time           : 2016:01:19 17:56:07+00:00
File Inode Change Date/Time     : 2016:01:18 11:39:09+00:00
File Permissions                : rw-r--r--
File Type                       : MOV
File Type Extension             : mov
MIME Type                       : video/quicktime
Major Brand                     : Apple QuickTime (.MOV/QT)
Minor Version                   : 0.0.0
Compatible Brands               : qt
Movie Data Size                 : 2430692
Movie Data Offset               : 36
Movie Header Version            : 0
Create Date                     : 2015:12:12 08:59:26
Modify Date                     : 2015:12:12 08:59:26
Time Scale                      : 600
Duration                        : 1.01 s
Preferred Rate                  : 1
Preferred Volume                : 100.00%
Preview Time                    : 0 s
Preview Duration                : 0 s
Poster Time                     : 0 s
Selection Time                  : 0 s
Selection Duration              : 0 s
Current Time                    : 0 s
Next Track ID                   : 3
Track Header Version            : 0
Track Create Date               : 2015:12:12 08:59:26
Track Modify Date               : 2015:12:12 08:59:26
Track ID                        : 1
Track Duration                  : 1.01 s
Track Layer                     : 0
Track Volume                    : 0.00%
Image Width                     : 1920
Image Height                    : 1080
Clean Aperture Dimensions       : 1920x1080
Production Aperture Dimensions  : 1920x1080
Encoded Pixels Dimensions       : 1920x1080
Graphics Mode                   : ditherCopy
Op Color                        : 32768 32768 32768
Compressor ID                   : avc1
Source Image Width              : 1920
Source Image Height             : 1080
X Resolution                    : 72
Y Resolution                    : 72
Compressor Name                 : H.264
Bit Depth                       : 24
Video Frame Rate                : 29.952
Matrix Structure                : 1 0 0 0 1 0 0 0 1
Media Header Version            : 0
Media Create Date               : 2015:12:12 08:59:26
Media Modify Date               : 2015:12:12 08:59:26
Media Time Scale                : 44100
Media Duration                  : 1.07 s
Media Language Code             : und
Balance                         : 0
Handler Class                   : Data Handler
Handler Vendor ID               : Apple
Handler Description             : Core Media Data Handler
Audio Format                    : mp4a
Audio Channels                  : 1
Audio Bits Per Sample           : 16
Audio Sample Rate               : 44100
Purchase File Format            : mp4a
Software Version                : 8.1.2
Content Create Date             : 2015:01:19 12:45:11-08:00
GPS Coordinates                 : 38 deg 11' 21.48" N, 119 deg 57' 20.88" W, 2004 m Above Sea Level
Make                            : Apple
Model                           : iPhone 5
Handler Type                    : Metadata Tags
Make (und-US)                   : Apple
Creation Date (und-US)          : 2015:01:19 12:45:11-08:00
GPS Coordinates (und-US)        : 38 deg 11' 21.48" N, 119 deg 57' 20.88" W, 2004 m Above Sea Level
Software (und-US)               : 8.1.2
Model (und-US)                  : iPhone 5
Creation Date                   : 2015:01:19 12:45:11-08:00
Software                        : 8.1.2
Avg Bitrate                     : 19.3 Mbps
GPS Altitude                    : 2004 m
GPS Altitude Ref                : Above Sea Level
GPS Latitude                    : 38 deg 11' 21.48" N
GPS Longitude                   : 119 deg 57' 20.88" W
GPS Position                    : 38 deg 11' 21.48" N, 119 deg 57' 20.88" W
Image Size                      : 1920x1080
Megapixels                      : 2.1
Rotation                        : 0
```

Note that on the old version `Creation Date (und-US)` is listed, but not `Creation Date` without the suffix.

**Comment by noonat** [comment]
Ubuntu 14.04's exiftool is 9.46, and it is also missing Creation Date without the suffix. I guess the code could check for the generic Creation Date first, then fall back on looking for one with a suffix?

**Comment by jmathai** [comment]
@noonat Thanks for that tip. Added your suggestion and it worked.
