### ISSUE TITLE
Set up different folder for config.ini

### ISSUE THREAD

**Issue by gti96** [jmathai/elodie#339]
> If you'd like to use a different folder for your configuration file then set an environment variable named ELODIE_APPLICATION_DIRECTORY with the fully qualified directory path.

Sorry I am new to python and linux so please bear with me.
I am not sure how to set an environment variable as mentioned above.
Is this environment variable for python or OS? 
Where am I supposed to set this? Is it in elodie.py or somewhere else? 

I have tried adding a line in elodie.py with os.environ but doesn't seem to do anything.

**Comment by gti96** [comment]
I think I got it all wrong at first and should be changing constants.py:
```
#: Directory in which to store Elodie settings.
application_directory = '/elodie'
```
And this is what I got:
```
Traceback (most recent call last):
  File "/elodie/elodie.py", line 359, in <module>
    main()
  File "/opt/lib/python3.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/lib/python3.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/lib/python3.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/lib/python3.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/lib/python3.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/elodie/elodie.py", line 128, in _import
    trash, allow_duplicates)
  File "/elodie/elodie.py", line 67, in import_file
    media, allowDuplicate=allow_duplicates, move=False)
  File "/elodie/elodie/filesystem.py", line 532, in process_file
    plugins_run_before_status = self.plugins.run_all_before(_file, destination)
  File "/elodie/elodie/plugins/plugins.py", line 202, in run_all_before
    self.load()
  File "/elodie/elodie/plugins/plugins.py", line 134, in load
    plugin_list = load_plugin_config()
  File "/elodie/elodie/config.py", line 22, in load_plugin_config
    config = load_config()
  File "/elodie/elodie/config.py", line 18, in load_config
    load_config.config.read(config_file)
  File "/configparser.py", line 696, in read
  File "/configparser.py", line 1110, in _read
configparser.ParsingError: Source contains parsing errors: '/elodie/config.ini'
        [line 36]: '~                                                                               \n'
        [line 37]: '~                                                                               \n'
        [line 38]: '~              
```

**Comment by gti96** [comment]
silly me. I got all these extra ~'s  at the end of config.ini file I did not realise. Got it working now using:
`environ['ELODIE_APPLICATION_DIRECTORY']='/elodie'
`

**Comment by jmathai** [comment]
Your solution works. I would recommend exporting to your environment without hard coding it in the source code. This lets you more easily pull updates of the code.

For linux you can add this to your `.bashrc` file or read [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps) for a more in depth look.

```
ELODIE_APPLICATION_DIRECTORY=/your/path
```

**Comment by gti96** [comment]
Thanks for the tutorial, jmathai.
I will definitely follow your recommendation.
