### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Jogai** [jmathai/elodie#346]
```
****** ERROR DETAILS ******
Traceback (most recent call last):
  File "./elodie.py", line 371, in <module>
    main()
  File "/home/wouter/.local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/wouter/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/wouter/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wouter/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wouter/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 144, in _import
    result.write()
  File "/home/wouter/src/elodie/elodie/result.py", line 29, in write
    print(tabulate(error_result, headers=error_headers))
  File "/home/wouter/.local/lib/python2.7/site-packages/tabulate.py", line 1119, in tabulate
    ['\t'.join(map(_text_type, row)) for row in list_of_lists])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 47: ordinal not in range(128)
```

How can I check which photo this fails on? Now it fails after 20 hours and I have to restart again.

**Comment by Jogai** [comment]
Sorry, exact issue is already described somewhere else
