### ISSUE TITLE
AttributeError: type object 'Media' has no attribute 'photo_extensions'

### ISSUE THREAD

**Issue by ibizaman** [jmathai/elodie#36]
When running a simple import, I get the following error:
```python
Traceback (most recent call last):
  File "./elodie.py", line 157, in <module>
    _import(params)
  File "./elodie.py", line 37, in _import
    media = Media.get_class_by_file(current_file, [Photo, Video])
  File "./elodie/elodie/media/media.py", line 298, in get_class_by_file
    if(extension in Media.photo_extensions):
AttributeError: type object 'Media' has no attribute 'photo_extensions'
```

I'm on `master - 5818978` and all tests seem to pass fine:
```
nosetests -s
..............S.S....S...********************.S********************.S......................
----------------------------------------------------------------------
Ran 51 tests in 10.250s

OK (SKIP=5)
```

I outputted some values if that can help:
```python
>>> Media.__class__
<class 'elodie.media.media.Media'>

>>> dir(Media)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__',
'__hash__', '__init__', '__module__', '__name__', '__new__', '__reduce__',
'__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__',
'__weakref__', 'get_album', 'get_class_by_file', 'get_exif', 'get_exiftool',
'get_exiftool_attributes', 'get_extension', 'get_file_path', 'get_metadata',
'get_mimetype', 'get_title', 'is_valid', 'set_album', 'set_album_from_folder',
'set_metadata', 'set_metadata_basename']
```

**Comment by jmathai** [comment]
Looks like there were missing tests on `Media.get_class_by_file`. I've added them and verified that the tests failed prior to my commit and passed after.

Before
```
..EEE
======================================================================
ERROR: elodie.tests.media.media_test.test_get_class_by_file_photo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/jaisenmathai/dev/tools/elodie/elodie/tests/media/media_test.py", line 36, in test_get_class_by_file_photo
    media = Media.get_class_by_file(helper.get_file('plain.jpg'), [Photo, Video])
  File "/Users/jaisenmathai/dev/tools/elodie/elodie/media/media.py", line 297, in get_class_by_file
    if(extension in Media.photo_extensions):
AttributeError: type object 'Media' has no attribute 'photo_extensions'

======================================================================
ERROR: elodie.tests.media.media_test.test_get_class_by_file_video
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/jaisenmathai/dev/tools/elodie/elodie/tests/media/media_test.py", line 41, in test_get_class_by_file_video
    media = Media.get_class_by_file(helper.get_file('video.mov'), [Photo, Video])
  File "/Users/jaisenmathai/dev/tools/elodie/elodie/media/media.py", line 297, in get_class_by_file
    if(extension in Media.photo_extensions):
AttributeError: type object 'Media' has no attribute 'photo_extensions'

======================================================================
ERROR: elodie.tests.media.media_test.test_get_class_by_file_unsupported
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/jaisenmathai/dev/tools/elodie/elodie/tests/media/media_test.py", line 46, in test_get_class_by_file_unsupported
    media = Media.get_class_by_file(helper.get_file('text.txt'), [Photo, Video])
  File "/Users/jaisenmathai/dev/tools/elodie/elodie/media/media.py", line 297, in get_class_by_file
    if(extension in Media.photo_extensions):
AttributeError: type object 'Media' has no attribute 'photo_extensions'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=3)
```

After
```
➜  elodie git:(gh-36-attribute-error) ✗ nosetests elodie/tests/media/media_test.py
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
```
