### ISSUE TITLE
Installing elodie fails on MacOS Sonoma 14.5 (23F79) using Python 3.13.0 

### ISSUE THREAD

**Issue by bassqualle** [jmathai/elodie#473]
Prior installing elodie I installed Python 3.13.0 on MacOS 14.5

Runnning `pip install -r requirements.txt `fails with the following error.

```
Collecting Pillow==9.3 (from -r requirements.txt (line 8))
  Using cached Pillow-9.3.0.tar.gz (50.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
          exec(compile('''
          ~~~~^^^^^^^^^^^^
          # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ...<31 lines>...
          exec(compile(setup_py_code, filename, "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ''' % ('/private/var/folders/2q/ygw576jx1_b_hv4t302d2dlc0000gn/T/pip-install-tyds98li/pillow_2d6b86140cdf431ca590709c15d66ad4/setup.py',), "<pip-setuptools-caller>", "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/2q/ygw576jx1_b_hv4t302d2dlc0000gn/T/pip-install-tyds98li/pillow_2d6b86140cdf431ca590709c15d66ad4/setup.py", line 29, in <module>
          PILLOW_VERSION = get_version()
        File "/private/var/folders/2q/ygw576jx1_b_hv4t302d2dlc0000gn/T/pip-install-tyds98li/pillow_2d6b86140cdf431ca590709c15d66ad4/setup.py", line 26, in get_version
          return locals()["__version__"]
                 ~~~~~~~~^^^^^^^^^^^^^^^
      KeyError: '__version__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I assume the affected package isn't working with a new python version.

Could you help?

**Comment by jmathai** [comment]
There are some known issues with pythong 3.10+. Unfortunately, the app is blocked on supporting newer versions of python because (last time I checked) nosetests are not supported on 3.10+ and the test suite is large (larger LOC than the application itself).

Here's another thread with some possible workarounds - but basically, I suggest running it in a 3.9 virtual environment.

https://github.com/jmathai/elodie/issues/418

**Comment by bassqualle** [comment]
Thanks for your reply. I will give it a try to work around it.
