### ISSUE TITLE
Image missing DateTimeOriginal causes a traceback

### ISSUE THREAD

**Issue by noonat** [jmathai/elodie#74]
It looks like an image that is missing the DateTimeOriginal EXIF tag causes a traceback when trying to update the file:

```python
$ ./elodie.py update --time='2015-01-02' '/export/2015-01-Jan/Unknown Location/2015-01-01_00-00-00-test.jpg'
Traceback (most recent call last):
  File "./elodie.py", line 217, in <module>
    sys.exit(main())
  File "./elodie.py", line 212, in main
    _update(params)
  File "./elodie.py", line 156, in _update
    updated = update_time(media, file_path, params['--time'])
  File "./elodie.py", line 130, in update_time
    media.set_date_taken(time)
  File "/opt/elodie/elodie/media/photo.py", line 174, in set_date_taken
    exif_metadata['Exif.Photo.DateTimeOriginal'].value = time
  File "/usr/lib/python2.7/site-packages/pyexiv2/metadata.py", line 209, in __getitem__
    return getattr(self, '_get_%s_tag' % family)(key)
  File "/usr/lib/python2.7/site-packages/pyexiv2/metadata.py", line 169, in _get_exif_tag
    _tag = self._image._getExifTag(key)
KeyError: 'Tag not set'
```

**Comment by jmathai** [comment]
@noonat Good catch. Writing EXIF differs when the tag isn't already set. Fixed and added a test.
